#############################################################################*#
#                                                                             #
# initInter.mac                                                               #
# Initialisation macro for interactive mode                                   #
#                                                                             #
###############################################################################
#
/control/verbose 2 
/control/saveHistory
#/run/verbose 2
#
# (Edit the next line(s) to choose another graphic system)
#/vis/open OGL
#/vis/open DANWFILE
#/vis/open Xo
#
/tracking/storeTrajectory 1
#
#
/control/execute vis.mac
# Camera viewpoint
#/vis/drawView  70 -90 0. 0. cm 1.5
#
# Add detector to scene
#/vis/drawVolume
#
#adding scale and axes
#/vis/scene/add/axes 100 100 100 100 cm    # Simple axes: x=red, y=green, z=blue.
#/vis/scene/add/eventID                   # Drawn at end of event
# Flush visualization
#/vis/viewer/update
#
# now run macro: gamma.mac, alpha.mac, neutron.mac


